// Copyright (c) 2026 Michael Lechner
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

package render

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"gitpulsemcl/pkg/config"
	"gitpulsemcl/pkg/gitmonitor"
)

func ShortenPath(path string, prefix string, replacement string) string {
	if prefix == "" {
		return path
	}
	if strings.HasPrefix(path, prefix) {
		return strings.Replace(path, prefix, replacement, 1)
	}
	return path
}
// HTML Output for eMails etc. -optionally  no colors, but basic formatting and a summary box at the end.
func HTML(version string, results []*gitmonitor.RepoStatus, summary gitmonitor.Summary, colored bool, settings config.Settings) {
	now := time.Now().Format("2006-01-02 15:04:05")
	fmt.Println("<!DOCTYPE html>")
	fmt.Println("<html><head><meta charset=\"UTF-8\">")
	fmt.Println("<style>")
	fmt.Println("  body { font-family: sans-serif; font-size: 14px; color: #111827; background-color: #ffffff; padding: 20px; }")
	fmt.Println("  table { border-collapse: collapse; width: 100%; margin-bottom: 20px; background-color: #ffffff; }")
	fmt.Println("  th, td { text-align: left; padding: 12px 10px; border-bottom: 1px solid #e5e7eb; }")
	fmt.Println("  th { background-color: #1f2937; color: #ffffff; text-transform: uppercase; font-size: 12px; letter-spacing: 0.05em; }")
	fmt.Println("  tr:hover { background-color: #f9fafb; }")

	if colored {
		fmt.Println("  .dirty { color: #b45309; font-weight: bold; }")
		fmt.Println("  .clean { color: #059669; }")
		fmt.Println("  .error { color: #dc2626; font-weight: bold; }")
		fmt.Println("  .no-remote { color: #0891b2; font-style: italic; font-size: 12px; }")
		fmt.Println("  .muted { color: #6b7280; font-size: 12px; }")
		fmt.Println("  .ahead { color: #2563eb; font-weight: bold; }")
	} else {
		fmt.Println("  .dirty, .clean, .error, .no-remote, .muted, .ahead { color: #111827; }")
	}

	fmt.Println("  .summary-box { padding: 20px; background: #f9fafb; border: 1px solid #d1d5db; border-radius: 8px; display: inline-block; color: #111827; }")
	fmt.Println("  .summary-item { margin-right: 20px; }")
	fmt.Println("  .footer { margin-top: 30px; font-size: 11px; color: #9ca3af; border-top: 1px solid #f3f4f6; padding-top: 10px; }")
	fmt.Println("</style></head><body>")

	fmt.Printf("<h2>GitPulseMLC Report</h2>")
	fmt.Printf("<p class=\"muted\">Report generated on: <strong>%s</strong></p>\n", now)

	fmt.Println("<table><thead><tr><th>Project Name</th><th>Active Branch</th><th>Status</th><th>Local Path</th></tr></thead><tbody>")

	for _, s := range results {
		statusClass := "clean"
		statusText := "CLEAN"
		if s.ErrorMsg != "" {
			statusClass = "error"
			statusText = "ERROR: " + s.ErrorMsg
		} else if !s.IsClean {
			statusClass = "dirty"
			statusText = "DIRTY"
			if len(s.ChangedFiles) > 0 {
				var parts []string
				keys := make([]string, 0, len(s.ChangedFiles))
				for k := range s.ChangedFiles { keys = append(keys, k) }
				sort.Strings(keys)
				for _, k := range keys { parts = append(parts, fmt.Sprintf("%d%s", s.ChangedFiles[k], k)) }
				statusText += fmt.Sprintf(" (%s)", strings.Join(parts, ", "))
			}
		}

		noRemoteTag := ""
		if s.HasNoRemote {
			noRemoteTag = " <span class=\"no-remote\">(No Remote)</span>"
		}

		displayPath := ShortenPath(s.Path, settings.ReplacePathPrefix, settings.ReplaceWith)

		fmt.Printf("<tr><td><strong style=\"color: #111827;\">%s</strong></td><td><code>%s</code></td><td class=\"%s\">%s%s</td><td class=\"muted\">%s</td></tr>\n",
			s.Name, s.CurrentBranch, statusClass, statusText, noRemoteTag, displayPath)
	}

	fmt.Println("</tbody></table>")

	fmt.Println("<div class=\"summary-box\">")
	fmt.Println("<strong style=\"font-size: 16px; display: block; margin-bottom: 10px;\">Summary</strong>")
	fmt.Printf("<span class=\"summary-item\">Total: <strong>%d</strong></span>", summary.Total)
	fmt.Printf("<span class=\"summary-item\">Dirty: <strong class=\"dirty\">%d</strong></span>", summary.Dirty)
	fmt.Printf("<span class=\"summary-item\">Ahead: <strong style=\"color: #2563eb;\">%d</strong></span>", summary.Ahead)
	fmt.Printf("<span class=\"summary-item\">Behind: <strong class=\"error\">%d</strong></span>", summary.Behind)
	fmt.Printf("<span class=\"summary-item\">Errors: <strong class=\"error\">%d</strong></span>", summary.Errors)
	fmt.Println("</div>")

	fmt.Printf("<div class=\"footer\">Generated by GitPulseMLC v%s | Michael Lechner</div>\n", version)
	fmt.Println("</body></html>")
}
